---
abstract: 'The right way to convert nested callback in plain struct or just the syntax sugar for guy who do not like deep indent.'
author:
  - 'Anton Reznikov <a.reznikov@corp.mail.ru>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Async-Chain
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
version: 0.05
